### ISSUE TITLE
该章节图中有一个小错漏的地方，详见描述

### ISSUE THREAD

**Issue by aaron-codes** [tonydeng/EA-practices#1]
很赞的架构经验总结，该章节图中有一个小错漏的地方。

[企业架构方法论概述](https://tonydeng.github.io/EA-practices/ea-methods/overview.html#%E4%BC%81%E4%B8%9A%E6%9E%B6%E6%9E%84%E6%96%B9%E6%B3%95%E8%AE%BA%E6%A6%82%E8%BF%B0)
<img width="883" alt="image" src="https://github.com/tonydeng/EA-practices/assets/3776267/1e4754b5-1026-4c20-9a46-68be41ed3135">

**Comment by tonydeng** [comment]
谢谢，已经修复 https://github.com/tonydeng/EA-practices/commit/24770cb3dcfe69ac9866a947450ee53a03fac9b8
